### ISSUE TITLE
Dump by hostname/domain

### ISSUE THREAD

**Issue by ocket8888** [Comcast/Superior-Cache-ANalyzer#7]
Currently, `-d`/`--dump` only supports output sorted by url. However, it'd be nice to be able to dump all of the content stored according to hostname/domain, e.g.
```YAML
...
steampowered.com:
    docs: 170
    total_size: 38GB
play.google.com:
    docs: 82
    total_size: 5.2GB
...
```
